//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace onlineHospital.sites.Patient_Site {
    
    
    public partial class patient {
        
        /// <summary>
        /// articleControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::onlineHospital.CodeControl.articleControl articleControl;
        
        /// <summary>
        /// articleControl1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::onlineHospital.CodeControl.articleControl articleControl1;
        
        /// <summary>
        /// articleControl2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::onlineHospital.CodeControl.articleControl articleControl2;
        
        /// <summary>
        /// articleControl3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::onlineHospital.CodeControl.articleControl articleControl3;
        
        /// <summary>
        /// articleControl4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::onlineHospital.CodeControl.articleControl articleControl4;
    }
}
