//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace onlineHospital.PublicSite {
    
    
    public partial class viewDoctors {
        
        /// <summary>
        /// doctorInfoControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::onlineHospital.CodeControl.doctorInfoControl1 doctorInfoControl;
        
        /// <summary>
        /// doctorInfoControl1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::onlineHospital.CodeControl.doctorInfoControl1 doctorInfoControl1;
        
        /// <summary>
        /// doctorInfoControl2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::onlineHospital.CodeControl.doctorInfoControl1 doctorInfoControl2;
        
        /// <summary>
        /// articleControl4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::onlineHospital.CodeControl.articleControl articleControl4;
        
        /// <summary>
        /// articleControl3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::onlineHospital.CodeControl.articleControl articleControl3;
        
        /// <summary>
        /// articleControl2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::onlineHospital.CodeControl.articleControl articleControl2;
    }
}
